from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.preprocess.base import initialize_canonical_tables, list_dataset_ids, scan_raw_inventory
from src.utils.constants import PROJECT_ROOT
from src.utils.io import write_json


def parse_dataset_selection(raw_value: str) -> list[str]:
    if raw_value == "all":
        return list_dataset_ids()
    selected = [item.strip() for item in raw_value.split(",") if item.strip()]
    unknown = sorted(set(selected) - set(list_dataset_ids()))
    if unknown:
        raise ValueError(f"Unknown dataset ids: {unknown}")
    return selected


def build_schema_audit_markdown(records: list[dict]) -> str:
    lines = [
        "# Schema Audit",
        "",
        f"Generated: `{datetime.now(timezone.utc).isoformat()}`",
        "",
        "This audit was generated by the minimal preprocessing scaffold. Raw parsing is not complete yet; tables are canonical placeholders designed to lock the schema and surface environment issues early.",
        "",
        "| Dataset | Raw files detected | Participants table | Daily table | Anchors | Windows export | Concepts export | Notes |",
        "|---|---:|---|---|---|---|---|---|",
    ]

    for record in records:
        windows_note = record["artifacts"]["windows_record"]["format"]
        concepts_note = record["artifacts"]["concepts_record"]["format"]
        note = "empty canonical placeholders created"
        if record["artifacts"]["windows_record"]["fallback_reason"] or record["artifacts"]["concepts_record"]["fallback_reason"]:
            note = "parquet dependency missing; csv fallback written"
        lines.append(
            "| {dataset_id} | {raw_count} | {participants} | {daily} | {anchors} | {windows} | {concepts} | {note} |".format(
                dataset_id=record["dataset_id"],
                raw_count=record["raw_file_count"],
                participants=record["artifacts"]["participants_path"],
                daily=record["artifacts"]["raw_daily_path"],
                anchors=record["artifacts"]["anchors_path"],
                windows=windows_note,
                concepts=concepts_note,
                note=note,
            )
        )

    lines.extend(
        [
            "",
            "## Parquet export notes",
            "",
            "- If `pyarrow` is unavailable, placeholder tables are exported as CSV fallback while retaining the requested parquet target path in the manifest.",
            "- No study data have been parsed into features yet; row counts are expected to be zero at this stage.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate canonical placeholder tables and schema audit.")
    parser.add_argument("--dataset", default="all", help="Dataset id or comma-separated ids, or 'all'.")
    args = parser.parse_args()

    selected_datasets = parse_dataset_selection(args.dataset)
    records: list[dict] = []

    for dataset_id in selected_datasets:
        raw_inventory = scan_raw_inventory(dataset_id)
        artifacts = initialize_canonical_tables(dataset_id)
        records.append(
            {
                "dataset_id": dataset_id,
                "raw_file_count": len(raw_inventory),
                "raw_inventory": raw_inventory,
                "artifacts": artifacts,
            }
        )

    write_json(
        PROJECT_ROOT / "outputs" / "logs" / "minimal_preprocess_manifest.json",
        {
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "datasets": selected_datasets,
            "records": records,
        },
    )

    audit_path = PROJECT_ROOT / "reports" / "qa" / "schema_audit.md"
    audit_path.write_text(build_schema_audit_markdown(records), encoding="utf-8")

    print(f"Wrote schema audit to {audit_path}")
    for record in records:
        print(
            f"{record['dataset_id']}: raw_files={record['raw_file_count']} "
            f"windows_format={record['artifacts']['windows_record']['format']} "
            f"concepts_format={record['artifacts']['concepts_record']['format']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
